supabse integration and crud operation implementation
shimlakanu/node-api pull request #1
Opened 2023-03-25 19:05 UTC by shimlakanu

2023-03-25 19:34 UTC, sadekujjaman requested changes
Looks good, Added a few comments to change.

2023-03-25 19:34 UTC, sadekujjaman commented on supabaseClient.js
> +// module.exports = supabase;
Please remove comments.

2023-03-25 19:34 UTC, sadekujjaman commented on supabaseClient.js
> + 'eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im5rem9rZG1oZmduenhpaXpudmdpIiwicm9sZSI6ImFub24iLCJpYXQiOjE2Nzk1OTczNTQsImV4cCI6MTk5NTE3MzM1NH0.8bY8vSA1LBE4_kirl1lIB7xNQM2PCzvL
Those are very sensitive info. Never share those info in public. 
Create a `.env` file and store those key in that file.
Your `.env` file will look something like this:
```
SUPABASE_URL = https://nkzokdmhfgnzxiiznvgi.supabase.co
SUPABASE_ANON_KEY = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im5rem9rZG1oZmduenhpaXpudmdpIiwicm9sZSI6ImFub24iLCJpYXQiOjE2Nzk1OTczNTQsImV4cCI6MTk5NTE3MzM1NH0.8bY8vSA1LBE4_kirl1lIB7xNQM2PCzvLam7BMsXkVH4

```

Then use those keys something like this:
```
const supabase = createClient(process.env.SUPABASE_URL, process.env.SUPABASE_ANON_KEY);
```

Now add the `.env` file in the `.gitignore`, so that git doesn't add this file.

To make things working, install dotenv package.

`npm install dotenv`

2023-03-25 19:34 UTC, sadekujjaman commented on index.js
> +    // console.log(data,error);
remove?

2023-03-25 19:34 UTC, sadekujjaman commented on index.js
> +    if (!flag && !error) res.send("no such tuple having this id exists");
How about getting a single user data directly from supabase?

```
const { data, error } = await supabase
        .from('user')
        .select()
        .eq('id', id)

```

2023-03-25 19:34 UTC, sadekujjaman commented on index.js
> +    console.log('post okay');
Get the data from req body not hard-coded.

2023-03-25 19:34 UTC, sadekujjaman commented on index.js
> +        .insert({ 'id': 66, 'created_at': "2022-07-21 14:08:04+00", 'name': "asd", 'age': 15 });
Also here, get the data from req body not hard-coded.

2023-03-25 19:34 UTC, sadekujjaman commented on index.js
> +        .update({ 'id': 20 })
Get the update info from req body, which field I'm going to update.

2023-03-26 07:04 UTC, shimlakanu commented on index.js
> +        .update({ 'id': 20 })
fixed :D

2023-03-26 07:09 UTC, sadekujjaman commented on index.js
> +        .eq('id', id);
Nice.

2023-03-26 07:10 UTC, sadekujjaman commented on supabaseClient.js
> +const supabase = createClient(supabaseUrl, supabaseKey);
Great.

2023-03-26 07:11 UTC, sadekujjaman approved these changes
Very good PR. Thanks for fixing all the issues. Go ahead for merging this branch.

2023-04-05 18:26 UTC, merged